### ISSUE TITLE
[Bug] New ponder version not identifying functions from abi & throwing "Reduce of empty array with no initial values" error on npm run dev

### ISSUE THREAD

**Issue by AndrewWangGit** [ponder-sh/ponder#1140]
Hi! I'm newer to Ponder development but have built some projects with the framework in the past. Recently, I've been starting a new hobby project & I'm having issues with the new version of Ponder. Here are my exact steps to recreate the error:

npm create ponder@latest

Etherscan contract url: https://holesky.etherscan.io/address/0xa377164fa45cff88ecf5afd00caaaba959bd0d02

PONDER_RPC_URL_17000=https://holesky.drpc.org

npm run dev

---------------------------------------------------------------------------------------------

The exact error I'm getting is this:
`TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at checkpointMin (file:///Users/wwang/Documents/lev-fun-ponder/node_modules/@ponder/core/src/utils/checkpoint.ts:152:15)
    at getOmnichainCheckpoint (file:///Users/wwang/Documents/lev-fun-ponder/node_modules/@ponder/core/src/sync/index.ts:301:7)
    at Object.getStartCheckpoint (file:///Users/wwang/Documents/lev-fun-ponder/node_modules/@ponder/core/src/sync/index.ts:767:14)
    at create (file:///Users/wwang/Documents/lev-fun-ponder/node_modules/@ponder/core/src/indexing/service.ts:185:44)
    at file:///Users/wwang/Documents/lev-fun-ponder/node_modules/@ponder/core/src/utils/extend.ts:15:21
    at run (file:///Users/wwang/Documents/lev-fun-ponder/node_modules/@ponder/core/src/bin/utils/run.ts:155:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at worker (file:///Users/wwang/Documents/lev-fun-ponder/node_modules/@ponder/core/src/bin/commands/dev.ts:83:37)
2:55:23 PM WARN  process    Received unhandledRejection, starting shutdown sequence
`
If anyone could give any insight into what's going wrong that would be amazing!

**Comment by kyscott18** [comment]
Hey @AndrewWangGit 

I dug into this a bit and I think that you may be on an out of date version of ponder. I believe we fixed this issue in v0.5.24 https://github.com/ponder-sh/ponder/releases/tag/%40ponder%2Fcore%400.5.24. Sometimes npm will use an old version unless you specifically tell it to use latest `npm create ponder@latest`.

The underlying issue is that there are now indexing functions registered, but now the error should be much more clear.
```sh
3:32:01 PM ERROR build      Failed build
BuildError: Validation failed: Found 0 registered indexing functions.
```

Going to close for now, feel free to reopen if the issue persists.
