### ISSUE TITLE
FlushError: numeric field overflow

### ISSUE THREAD

**Issue by pyk** [ponder-sh/ponder#1147]
Hey, my Ponder app is stuck at the following error:

```sh
2:46:24 AM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
2:46:24 AM ERROR indexing   Error while processing 'ERC20:Transfer' event in 'mainnet' block 5182354
FlushError: numeric field overflow
    at Object.update (/app/src/lib.ts:21:13)
    at createOrUpdateERC20 (/app/src/erc20/handler.ts:80:5)
  19 |         },
  20 |         async update(options) {
> 21 |             await db.ERC20.update(options)
     |             ^
  22 |         },
  23 |         async upsert(options) {
  24 |             await db.ERC20.upsert(options)
Event arguments:
  from    0x03c76E17E7aAA2356D92A61C6eFF8a0DAaeDE9c3
  to      0x81C56Da7623126b9C016ec0b7f4E430E1eD5D75e
  value   3450000
2:46:24 AM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
2:46:25 AM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
2:46:25 AM FATAL process    Finished shutdown sequence, terminating (exit code 1)

> @pyk/ponder@0.0.1 start
> ponder start

ERC20:Transfer ERROR:
erc20Id=0x3c4a3ffd813a107febd57B2f01BC344264D90FdE
fromAddress=0x03c76E17E7aAA2356D92A61C6eFF8a0DAaeDE9c3
toAddress=0x81C56Da7623126b9C016ec0b7f4E430E1eD5D75e
amount=3450000
tx=0x002abeafbef7f1c718fc7eb4b819c9529173219fbe3a5fbdc94c3f95a05bf912
npm notice
npm notice New minor version of npm available! 10.8.1 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
```

Here is my `ERC20` table:

```ts
    // ERC20
    ERC20: p.createTable({
        id: p.hex(),
        name: p.string().optional(),
        symbol: p.string().optional(),
        decimals: p.int().optional(),
        firstMintAtBlock: p.int(),
        firstMintAtTimestamp: p.int(),

        totalSupply: p.bigint(),
        holderCount: p.int(),
        nonCompliant: p.boolean(),
    })
```

Here is my `createOrUpdateERC20` implementation:

```ts
async function createOrUpdateERC20(params: HandleTransferERC20Params) {
    const { db, event, client, erc20Id, fromAddress, toAddress, amount } = params

    const erc20 = await db.ERC20.get({ id: erc20Id })
    if (erc20 == null) {
        const [name, symbol, decimals] = await Promise.all([
            getERC20Name({ client, address: erc20Id, blockNumber: event.block.number }),
            getERC20Symbol({ client, address: erc20Id, blockNumber: event.block.number }),
            getERC20Decimals({ client, address: erc20Id, blockNumber: event.block.number }),
        ])
        await db.ERC20.create({
            id: erc20Id,
            data: {
                name,
                symbol,
                decimals,
                totalSupply: amount,
                holderCount: 1,
                firstMintAtBlock: Number(event.block.number),
                firstMintAtTimestamp: Number(event.block.timestamp),
                nonCompliant: false,
            },
        })
        return
    }

    // Update
    let totalSupply = erc20.totalSupply
    let holderCount = erc20.holderCount

    if (fromAddress == zeroAddress) {
        totalSupply += amount
    }

    // Reduce holder count
    if (fromAddress != zeroAddress) {
        const fromHolder = await db.ERC20Holder.get({ id: `${erc20Id}-${fromAddress}` })
        if (fromHolder == null || fromHolder.balance < amount) {
            await db.ERC20.update({ id: erc20Id, data: () => ({ nonCompliant: true }) })
            return
        }
        const delta = fromHolder.balance - amount
        if (delta == 0n) {
            holderCount -= 1
        }
    }

    // Increase holder count
    const toHolder = await db.ERC20Holder.get({ id: `${erc20Id}-${toAddress}` })
    if (toHolder == null || toHolder.balance == 0n) {
        holderCount += 1
    }

    await db.ERC20.update({ id: erc20Id, data: () => ({ totalSupply, holderCount }) })
}
```

The only updated data are the `totalSupply` and `holderCount` fields. I’ve double-checked the token details on [Etherscan](https://etherscan.io/address/0x3c4a3ffd813a107febd57B2f01BC344264D90FdE#readContract), and both the holder count and total supply are within the normal range, well below the maximum values for `bigint` and `int`. So I'm not sure why Ponder is raising a numerical error here. 

Any ideas?

For additional context, I tried to index many events in one ponder app, here is my config:

```ts
import { createConfig } from "@ponder/core"
import { http } from "viem"

import { ERC721Abi } from "./abis/ERC721Abi"
import { ERC1155Abi } from "./abis/ERC1155Abi"
import { ERC20Abi } from "./abis/ERC20Abi"
import { WETH9Abi } from "./abis/WETH9Abi"
import { getChainConfig } from "./chain.config"

const chainConfig = getChainConfig()

export default createConfig({
    networks: {
        mainnet: {
            chainId: chainConfig.chainId,
            transport: http(chainConfig.rpcUrl),
            maxRequestsPerSecond: 15,
        },
    },
    contracts: {
        ERC20: {
            network: "mainnet",
            abi: ERC20Abi,
            startBlock: 0,
        },
        WETH9: {
            network: "mainnet",
            abi: WETH9Abi,
            address: chainConfig.weth9.address,
            startBlock: chainConfig.weth9.startBlock,
        },
        ERC721: {
            network: "mainnet",
            abi: ERC721Abi,
            startBlock: 0,
        },
        ERC1155: {
            network: "mainnet",
            abi: ERC1155Abi,
            startBlock: 0,
        },
    },
    database: {
        kind: "postgres",
        schema: `ponder_v2_${process.env.DEPLOYMENT_ID?.slice(0, 8)}`,
    },
})

```

lmk if I should split this into two ponder apps. thanks 🙏

**Comment by pyk** [comment]
It seems the problem is not with this [token](https://etherscan.io/address/0x3c4a3ffd813a107febd57B2f01BC344264D90FdE#readContract) or ponder internal, but with another token that has decimals greater than the maximum integer
