### ISSUE TITLE
 Internal error occurred while flushing cache.

### ISSUE THREAD

**Issue by MrKevinOConnell** [ponder-sh/ponder#1262]
this occurs on 0.7.7.

```5:56:55 AM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues

5:56:55 AM WARN  user       Failed 'component.flush()' database method 

5:56:55 AM ERROR process    Caught unhandledRejection event

FlushError: invalid input syntax for type json

    at file:///app/node_modules/@ponder/common/src/queue.ts:184:15

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

    at Object.flush (file:///app/node_modules/@ponder/core/src/indexing-store/historical.ts:794:7)

    at start3 (file:///app/node_modules/@ponder/core/src/bin/utils/run.ts:203:5)
```

note: addMetadata includes some synchronous logic that writes to other tables that *aren't* in the ponder.schema. 

example indexing function 
```
ponder.on(`something something`, async ({ event, context }) => {
  const componentId = event.args.unitId.toString();

  // Use memoized fetch and parallel processing
  const [metadataJson, existingComponent] = await Promise.all([
    addMetadata(event.args.unitHash, componentId),
    context.db.find(Component, { id: componentId }),
  ]);

  try {
    if (existingComponent) {
      await context.db.update(Component, {...}
      });
    } else {
      await context.db.insert(Component).values({
       ...
      });
    }
  } catch (e) {
    
  }

  //call
  try {
    const { client } = context;
    const { MainnetComponentRegistry } = context.contracts;
    const dependencies = await client.readContract({
      abi: MainnetComponentRegistry.abi,
      address: MainnetComponentRegistry.address,
      functionName: "getDependencies",
      args: [event.args.unitId],
    });

    if (
      dependencies &&
      Array.isArray(dependencies) &&
      dependencies.length === 2
    ) {
      const dependencyArray = dependencies[1];
      if (Array.isArray(dependencyArray) && dependencyArray.length > 0) {
        const validDependencies = dependencyArray
          .map((dep) => dep.toString())
          .filter((dep) => dep !== "")
          .map((dependency) => ({
          ...
          }));

        if (validDependencies.length > 0) {
          await context.db
            .insert(ComponentDependency)
            .values(validDependencies);
        }
      }
    }
  } catch (e) {
    // console.log("error processing dependencies:", e);
  }
});
```

**Comment by maxencerb** [comment]
Exact same issue here with this version
