### ISSUE TITLE
wasm error during first run

### ISSUE THREAD

**Issue by 3commascapital** [ponder-sh/ponder#1366]
### Version

0.8.7

### Current behavior

when first starting up, using pglite, i often run into the error below

### Expected behavior

for it to not lock up and error out

### Steps to reproduce

* choose `Reference - ERC20 token` in the create list
* set your rpc url
* run dev

### Anything else?

```
➜  indexer git:(master) ✗ bun run dev                 
$ ponder dev
1:53:00 PM INFO  build      Using PGlite database at .ponder/pglite (default)
1:53:00 PM WARN  build      Network 'pulsechain' is using a public RPC URL (https://rpc.pulsechain.com). Most apps require an RPC URL with a higher rate limit.
1:53:00 PM INFO  database   Using database schema 'public'
1:53:01 PM INFO  database   Created tables [account, burns, allowance, transfer_event, approval_event]
1:53:02 PM INFO  historical Started syncing 'pulsechain' with 0.0% cached
1:53:02 PM INFO  server     Started listening on port 42069
1:53:11 PM ERROR database   Failed to update heartbeat timestamp, retrying in 10s
RuntimeError: memory access out of bounds
    at null.<anonymous> (wasm://wasm/0222924a:1:4407052)
    at null.<anonymous> (wasm://wasm/0222924a:1:5775357)
    at null.<anonymous> (wasm://wasm/0222924a:1:5517304)
    at null.<anonymous> (wasm://wasm/0222924a:1:1277716)
    at null.<anonymous> (wasm://wasm/0222924a:1:1276955)
    at invoke_v (indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.15/node_modules/@electric-sql/pglite/release/postgres.js:9:2717108)
    at null.<anonymous> (wasm://wasm/0222924a:1:3860899)
    at I_.execProtocolRaw (indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.15/node_modules/@electric-sql/pglite/src/pglite.ts:596:9)
    at I_.execProtocol (indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.15/node_modules/@electric-sql/pglite/src/pglite.ts:623:29)
    at I_.o (indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.15/node_modules/@electric-sql/pglite/src/base.ts:130:23)
```

**Comment by jaylmiller** [comment]
> `indexer git:(master) ✗ bun run dev `

bun is not supported yet

**Comment by 3commascapital** [comment]
error during 0.8.8 during dev script using postgres
```
AggregateError: 
    at bridge-indexer/node_modules/.pnpm/ponder@0.8.8_@opentelemetry+api@1.9.0_@types+node@20.17.10_hono@4.6.14_typescript@5.7.2_viem@2.21.56_typescript@5.7.2_/node_modules/common/src/queue.ts:184:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
