### ISSUE TITLE
Failed 'Nft.flush()'

### ISSUE THREAD

**Issue by pursue-wind** [ponder-sh/ponder#1376]
### Version

0.7.17

### Current behavior

**This error only occurs on the Linux server. I've tried versions 0.7 and 0.8, and both have this error. Using a new database doesn't solve the problem either.**
It had been working properly all along, but suddenly this error occurred when starting it up. However, it starts up normally on my local Mac. 
```
7:10:19 AM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:10:19 AM WARN  user       Failed 'Nft.flush()' database method 
7:10:19 AM ERROR process    Caught unhandledRejection event
FlushError: invalid byte sequence for encoding "UTF8": 0x00
    at file:///home/ubuntu/nft_index_2_test/node_modules/@ponder/common/src/queue.ts:184:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.flush (file:///home/ubuntu/nft_index_2_test/node_modules/@ponder/core/src/indexing-store/historical.ts:754:7)
    at start3 (file:///home/ubuntu/nft_index_2_test/node_modules/@ponder/core/src/bin/utils/run.ts:188:9)

7:10:19 AM WARN  process    Received unhandledRejection, starting shutdown sequence
7:10:19 AM ERROR process    Caught unhandledRejection event
FlushError: invalid byte sequence for encoding "UTF8": 0x00
    at file:///home/ubuntu/nft_index_2_test/node_modules/@ponder/common/src/queue.ts:184:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.flush (file:///home/ubuntu/nft_index_2_test/node_modules/@ponder/core/src/indexing-store/historical.ts:754:7)
    at start3 (file:///home/ubuntu/nft_index_2_test/node_modules/@ponder/core/src/bin/utils/run.ts:188:9)
```

**Comment by typedarray** [comment]
Thanks for opening - need a bit more information:
1. Can you share the indexing function body where you insert `Nft` records? (if there are multiple, the most common one)
2. And if so, can you share a link to the contract that emitted the event?

We believe the null characters are coming from the decoded event body, for example in a free-text field of the event like "author" or "graffiti". I'm looking for a link to the specific event that might include the null characters so we can reproduce and fix this. Thanks.

**Comment by pursue-wind** [comment]
## Thank you for your reply. I've found that the error was caused by the tokenURI field, but I haven't located the specific data yet. I've temporarily resolved this issue by using the "replace" function. 
```
const replaceControlChars = (input: string, replacement: string = ""): string => {
  return input.replace(/[\x00-\x1F\x7F]/g, replacement);
};
```

## insert
```
await context.db
      .insert(dbNft)
      .values({
        id: tokenPk,
        ...chainIdContractAddress,
        tokenId: tokenId.toString(),
        ownerId: data.ownerId, // mint need owner
        tokenURI: tokenURI,
        ...
      });
```


## errorlog
```
0|nft_index  | 3:22:13 AM WARN  user       Failed 'Nft.flush()' database method 
0|nft_index  | 3:22:13 AM ERROR process    Caught unhandledRejection event
0|nft_index  | FlushError: invalid byte sequence for encoding "UTF8": 0x00
0|nft_index  |     at file:///home/ubuntu/nft_index/node_modules/@ponder/common/src/queue.ts:184:15
0|nft_index  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|nft_index  |     at Object.flush (file:///home/ubuntu/nft_index/node_modules/@ponder/core/src/indexing-store/historical.ts:754:7)
0|nft_index  |     at start3 (file:///home/ubuntu/nft_index/node_modules/@ponder/core/src/bin/utils/run.ts:216:5)
0|nft_index  | 3:22:13 AM WARN  process    Received unhandledRejection, starting shutdown sequence
0|nft_index  | 3:22:13 AM ERROR process    Caught unhandledRejection event
0|nft_index  | FlushError: invalid byte sequence for encoding "UTF8": 0x00
0|nft_index  |     at file:///home/ubuntu/nft_index/node_modules/@ponder/common/src/queue.ts:184:15
0|nft_index  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|nft_index  |     at Object.flush (file:///home/ubuntu/nft_index/node_modules/@ponder/core/src/indexing-store/historical.ts:754:7)
0|nft_index  |     at start3 (file:///home/ubuntu/nft_index/node_modules/@ponder/core/src/bin/utils/run.ts:216:5)
0|nft_index  | (node:2889820) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 172)
0|nft_index  | (Use `node --trace-warnings ...` to show where the warning was created)
0|nft_index  | 3:22:13 AM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
```

**Comment by typedarray** [comment]
Thanks for the additional information - could you please share a contract address / block explorer link? Happy to search for the offending event myself, we'd really like to get this fixed for other users.

**Comment by pursue-wind** [comment]
**block explorer link**: https://scan.alg2-test.algen.network/blocks
**contract event**: ERC721 Transfer 
**start block**: 7000000
**Nft save**: 
```
await context.db
      .insert(dbNft)
      .values({
        id: tokenPk,
        tokenId: tokenId.toString(),
        tokenURI:  call tokenURI method,
        ...
      });
```

**Comment by kyscott18** [comment]
Can you share your config and rpc provider? Do you have an idea of about which block this error occurs in?

**Comment by kyscott18** [comment]
One way you might be able to find the exact log causing the error would be do use `.match()` instead of `.replace()`.
