### ISSUE TITLE
Continual RPC timeout / HTTP request failure issues on Alchemy and Infura

### ISSUE THREAD

**Issue by faces-of-eth** [ponder-sh/ponder#562]
Even after the latest fixes from @kyscott18 I'm still experiencing timeout issues on both Infura and Alchemy, only indexing one smart contract. Stack trace below.

```
Server live at http://localhost:42069
file:///ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/_esm/utils/rpc.js:29
            errorInstance: new TimeoutError({ body, url }),
                           ^

TimeoutError: The request took too long to respond.

URL: https://eth-mainnet.g.alchemy.com/v2/2kuEqToXp1Hl5K1jeCXhAa...
Request body: {"method":"eth_getBlockByNumber","params":["0x121469f",true]}

Details: The request timed out.
Version: viem@1.21.1
    at Object.http (file:///ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/utils/rpc.ts:115:24)
    at fn (file:///ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/clients/transports/http.ts:107:28)
    at Object.request (file:///ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/clients/transports/http.ts:109:45)
    at processQueue (file:///ponder/packages/core/src/utils/requestQueue.ts:90:12)
    at Timeout._onTimeout (file:///ponder/packages/core/src/utils/requestQueue.ts:111:9)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  details: 'The request timed out.',
  docsPath: undefined,
  metaMessages: [
    'URL: https://eth-mainnet.g.alchemy.com/v2/2kuEqToXp1Hl5K1jeCXhAa...',
    'Request body: {"method":"eth_getBlockByNumber","params":["0x121469f",true]}'
  ],
  shortMessage: 'The request took too long to respond.',
  version: 'viem@1.21.1'
}

Node.js v21.4.0
 ELIFECYCLE  Command failed with exit code 1.
 ```

There are no visible errors on either my Infura or Alchemy dashboard that might lead to any insight as to what's causing the problem.

Haven't looked into the cause, but potentially is being able to set a timeout threshold an opportunity to get around these things?

**Comment by faces-of-eth** [comment]
Update, discovering the VIEM timeout parameter I was able to bypass some of this, but making RPC calls along side indexing continually throws the timeout error.

My current network config:

```
export default createConfig({
  networks: {
    ethereum: {
      chainId: 1,
      transport: http(process.env.PONDER_RPC_URL_ETH, { timeout: 90_000 }),
    },
    ethereumAltRpc: {
      chainId: 1,
      transport: http(process.env.PONDER_RPC_URL_ETH_ALT, { timeout: 90_000 })
    },
    optimism: {
      chainId: 10,
      transport: http(process.env.PONDER_RPC_URL_OP, { timeout: 90_000 }),
      maxBlockRange: 10000
    },
  },
  ```

**Comment by faces-of-eth** [comment]
After updating to the above, still receiving errors on fetching rpc endpoints, but nothing in the Alchemy RPC.

```

Indexing (up to Sep 5, 2021)
██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 17.5% | 22512/128598 events (239228 total)

GraphQL 
Server live at http://localhost:42069
file://ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/_esm/utils/rpc.js:56
        throw new HttpRequestError({
              ^

HttpRequestError: HTTP request failed.

URL: https://opt-mainnet.g.alchemy.com/v2/W3v-wntQBUXFk5rusM3p...
Request body: {"method":"eth_getBlockByNumber","params":["0x6d3b948",true]}

Details: fetch failed
Version: viem@1.21.1
    at Object.http (file://ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/utils/rpc.ts:142:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:449:9)
    at fn (file://ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/clients/transports/http.ts:107:18)
    at Object.request (file://ponder-graph/node_modules/.pnpm/viem@1.21.1_typescript@5.3.3/node_modules/viem/clients/transports/http.ts:109:39) {
  details: 'fetch failed',
  docsPath: undefined,
  metaMessages: [
    'URL: https://opt-mainnet.g.alchemy.com/v2/W3v-wntQBUXFk5rusM3p...',
    'Request body: {"method":"eth_getBlockByNumber","params":["0x6d3b948",true]}'
  ],
  shortMessage: 'HTTP request failed.',
  version: 'viem@1.21.1',
  body: { method: 'eth_getBlockByNumber', params: [ '0x6d3b948', true ] },
  headers: undefined,
  status: undefined,
  url: 'https://opt-mainnet.g.alchemy.com/v2/W3v-wntQBUXFk5rusM3p...'
}

Node.js v21.4.0
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by kyscott18** [comment]
When you say "making RPC calls along side indexing" what do you mean?

**Comment by faces-of-eth** [comment]
> When you say "making RPC calls along side indexing" what do you mean?

<img width="918" alt="image" src="https://github.com/ponder-sh/ponder/assets/108703161/0ae81377-3e4d-42f3-b216-a17b639c547e">


Using `client.readContract`

**Comment by faces-of-eth** [comment]
Finally got this to work with the following settings in my `ponder.config`. Reached out to both Infura and Alchemy who say this is a client-side error. I might try another RPC like Chainstack just to verify.

```
const transportOpts: HttpTransportConfig = {
  retryCount: 10,
  timeout: 100_000,
};

const alchemy_eth = http(
  process.env.RPC_ETH_ALC,
  transportOpts
);
const alchemy_eth_2 = http(
  process.env.RPC_ETH_ALC_2,
  transportOpts
);
const infura_eth = http(
  process.env.RPC_ETH_INFURA,
  transportOpts
);
const alchemy_op = http(
  process.env.RPC_OP_ALC,
  transportOpts
);
const infura_op = http(
  process.env.RPC_OP_INFURA,
  transportOpts
);

export default createConfig({
  networks: {
    ethereum: {
      chainId: 1,
      transport: fallback(
        [alchemy_eth, infura_eth, alchemy_eth_2],
        { rank: true }
      ),
    },
    optimism: {
      chainId: 10,
      transport: fallback(
        [alchemy_op, infura_op],
        { rank: true }
      ),
    },
  },
  ...
}
```

**Comment by 0xOlias** [comment]
Thanks. What version of Ponder were you running when it began working using the fallback transport?

**Comment by faces-of-eth** [comment]
I believe 0.1.6 !
