### ISSUE TITLE
Invalid parameters were provided to the RPC method

### ISSUE THREAD

**Issue by Inkvi** [ponder-sh/ponder#833]
Starting with v0.4.9 there is a regression observed in my ponder setup:

```
InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: https://opt-sepolia.g.alchemy.com/v2/<id>
Request body: {"method":"eth_getLogs","params":[{"fromBlock":"0xa8f3a9","toBlock":"0xa9b6f8","topics":[["0x20fd8a5856711b18d00def4aa6abafbe00ce6d60795e015cc1cad35eb9b46359","0xf910705a7a768eb5958f281a5f84cae8bffc5dd811ca5cd303dda140a423698c","0xcf8be9ab2b5edf8beb2c45abe8e0cc7646318ac19f6c3164ba2e19e93a8a32af","0xe80f571f70f7cabf9d7ac60ece08421be374117776c311c327a083ca398f802f","0xe893e4ba0e364cdc96364b1e1e0d53b0d91e5fd6aa0ee9d81a17ecd61178bf17","0xb5bff96e18da044e4e34510d16df9053b9f1920f6a960732e5aaf22fe9b80136","0xa32e6f42b1d63fb83ad73b009a6dbb9413d1da02e95b1bb08f081815eea8db20","0xde5b57e6566d68a30b0979431df3d5df6db3b9aa89f8820f595b9315bf86d067","0xe46f6591236abe528fe47a3b281fb002524dadd3e62b1f317ed285d07273c3b1"]],"address":"0x8957494ccd4b085133e9a8d3600b766427d4976a"}]}

Details: Log response size exceeded. You can make eth_getLogs requests with up to a 2K block range and no limit on the response size, or you can request any block range with a cap of 10K logs in the response. Based on your parameters and the response size limit, this block range should work: [0xa8f3a9, 0xa927df]
Version: viem@1.21.3
    at withRetry.delay.count.count (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/buildRequest.ts:146:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at attemptRetry (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/promise/withRetry.ts:37:22)
```

**Comment by 0xOlias** [comment]
Hi, thanks for reporting. Did this throw an error / crash your server, or just a warning? It would be helpful if you could provide the logs above and below this.

**Comment by Inkvi** [comment]
It didn't crash the server but I am worried that it can caused events not to be processed.

Here are the logs with context:
```
4:27:11 PM INFO  historical Started sync with 3.9% cached (contract=sim network=base)
4:27:11 PM INFO  historical Started sync with 0.0% cached (contract=proof network=base)
4:27:13 PM ERROR Request failed
InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: https://opt-sepolia.g.alchemy.com/v2/J1EvgyNWEiBHllMcgEa-SWVkJBERKjPt
Request body: {"method":"eth_getLogs","params":[{"fromBlock":"0xa8d63d","toBlock":"0xa9998c","topics":[["0x20fd8a5856711b18d00def4aa6abafbe00ce6d60795e015cc1cad35eb9b46359","0xf910705a7a768eb5958f281a5f84cae8bffc5dd811ca5cd303dda140a423698c","0xcf8be9ab2b5edf8beb2c45abe8e0cc7646318ac19f6c3164ba2e19e93a8a32af","0xe80f571f70f7cabf9d7ac60ece08421be374117776c311c327a083ca398f802f","0xe893e4ba0e364cdc96364b1e1e0d53b0d91e5fd6aa0ee9d81a17ecd61178bf17","0xb5bff96e18da044e4e34510d16df9053b9f1920f6a960732e5aaf22fe9b80136","0xa32e6f42b1d63fb83ad73b009a6dbb9413d1da02e95b1bb08f081815eea8db20","0xde5b57e6566d68a30b0979431df3d5df6db3b9aa89f8820f595b9315bf86d067","0xe46f6591236abe528fe47a3b281fb002524dadd3e62b1f317ed285d07273c3b1"]],"address":"0x8957494ccd4b085133e9a8d3600b766427d4976a"}]}

Details: Log response size exceeded. You can make eth_getLogs requests with up to a 2K block range and no limit on the response size, or you can request any block range with a cap of 10K logs in the response. Based on your parameters and the response size limit, this block range should work: [0xa8d63d, 0xa927d6]
Version: viem@1.21.3
    at withRetry.delay.count.count (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/buildRequest.ts:146:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at attemptRetry (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/promise/withRetry.ts:37:22)
4:27:13 PM ERROR Request failed
InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: https://opt-sepolia.g.alchemy.com/v2/J1EvgyNWEiBHllMcgEa-SWVkJBERKjPt
Request body: {"method":"eth_getLogs","params":[{"fromBlock":"0xa9998d","toBlock":"0xaa0572","topics":[["0x20fd8a5856711b18d00def4aa6abafbe00ce6d60795e015cc1cad35eb9b46359","0xf910705a7a768eb5958f281a5f84cae8bffc5dd811ca5cd303dda140a423698c","0xcf8be9ab2b5edf8beb2c45abe8e0cc7646318ac19f6c3164ba2e19e93a8a32af","0xe80f571f70f7cabf9d7ac60ece08421be374117776c311c327a083ca398f802f","0xe893e4ba0e364cdc96364b1e1e0d53b0d91e5fd6aa0ee9d81a17ecd61178bf17","0xb5bff96e18da044e4e34510d16df9053b9f1920f6a960732e5aaf22fe9b80136","0xa32e6f42b1d63fb83ad73b009a6dbb9413d1da02e95b1bb08f081815eea8db20","0xde5b57e6566d68a30b0979431df3d5df6db3b9aa89f8820f595b9315bf86d067","0xe46f6591236abe528fe47a3b281fb002524dadd3e62b1f317ed285d07273c3b1"]],"address":"0x8957494ccd4b085133e9a8d3600b766427d4976a"}]}

Details: Log response size exceeded. You can make eth_getLogs requests with up to a 2K block range and no limit on the response size, or you can request any block range with a cap of 10K logs in the response. Based on your parameters and the response size limit, this block range should work: [0xa9998d, 0xa99a6a]
Version: viem@1.21.3
    at withRetry.delay.count.count (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/buildRequest.ts:146:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at attemptRetry (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/promise/withRetry.ts:37:22)
4:27:13 PM ERROR Request failed
InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: https://opt-sepolia.g.alchemy.com/v2/J1EvgyNWEiBHllMcgEa-SWVkJBERKjPt
Request body: {"method":"eth_getLogs","params":[{"fromBlock":"0xa97971","toBlock":"0xa9998c","topics":[["0x20fd8a5856711b18d00def4aa6abafbe00ce6d60795e015cc1cad35eb9b46359","0xf910705a7a768eb5958f281a5f84cae8bffc5dd811ca5cd303dda140a423698c","0xcf8be9ab2b5edf8beb2c45abe8e0cc7646318ac19f6c3164ba2e19e93a8a32af","0xe80f571f70f7cabf9d7ac60ece08421be374117776c311c327a083ca398f802f","0xe893e4ba0e364cdc96364b1e1e0d53b0d91e5fd6aa0ee9d81a17ecd61178bf17","0xb5bff96e18da044e4e34510d16df9053b9f1920f6a960732e5aaf22fe9b80136","0xa32e6f42b1d63fb83ad73b009a6dbb9413d1da02e95b1bb08f081815eea8db20","0xde5b57e6566d68a30b0979431df3d5df6db3b9aa89f8820f595b9315bf86d067","0xe46f6591236abe528fe47a3b281fb002524dadd3e62b1f317ed285d07273c3b1"]],"address":"0x8957494ccd4b085133e9a8d3600b766427d4976a"}]}

Details: Log response size exceeded. You can make eth_getLogs requests with up to a 2K block range and no limit on the response size, or you can request any block range with a cap of 10K logs in the response. Based on your parameters and the response size limit, this block range should work: [0xa97971, 0xa979eb]
Version: viem@1.21.3
    at withRetry.delay.count.count (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/buildRequest.ts:146:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at attemptRetry (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/promise/withRetry.ts:37:22)
4:27:14 PM ERROR Request failed
InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: https://opt-sepolia.g.alchemy.com/v2/J1EvgyNWEiBHllMcgEa-SWVkJBERKjPt
Request body: {"method":"eth_getLogs","params":[{"fromBlock":"0xa927d7","toBlock":"0xa97970","topics":[["0x20fd8a5856711b18d00def4aa6abafbe00ce6d60795e015cc1cad35eb9b46359","0xf910705a7a768eb5958f281a5f84cae8bffc5dd811ca5cd303dda140a423698c","0xcf8be9ab2b5edf8beb2c45abe8e0cc7646318ac19f6c3164ba2e19e93a8a32af","0xe80f571f70f7cabf9d7ac60ece08421be374117776c311c327a083ca398f802f","0xe893e4ba0e364cdc96364b1e1e0d53b0d91e5fd6aa0ee9d81a17ecd61178bf17","0xb5bff96e18da044e4e34510d16df9053b9f1920f6a960732e5aaf22fe9b80136","0xa32e6f42b1d63fb83ad73b009a6dbb9413d1da02e95b1bb08f081815eea8db20","0xde5b57e6566d68a30b0979431df3d5df6db3b9aa89f8820f595b9315bf86d067","0xe46f6591236abe528fe47a3b281fb002524dadd3e62b1f317ed285d07273c3b1"]],"address":"0x8957494ccd4b085133e9a8d3600b766427d4976a"}]}

Details: Log response size exceeded. You can make eth_getLogs requests with up to a 2K block range and no limit on the response size, or you can request any block range with a cap of 10K logs in the response. Based on your parameters and the response size limit, this block range should work: [0xa927d7, 0xa92ace]
Version: viem@1.21.3
    at withRetry.delay.count.count (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/buildRequest.ts:146:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at attemptRetry (file:///Users/inkvi/dev/evm-indexer/node_modules/viem/utils/promise/withRetry.ts:37:22)
4:27:21 PM INFO  historical Sync is 30.9% complete with ~28s remaining (contract=sim)
4:27:21 PM INFO  historical Sync is 31.0% complete with ~27s remaining (contract=proof)
4:27:21 PM INFO  historical Sync is 6.2% complete with ~6m 44s remaining (contract=sim)
```

**Comment by jaylmiller** [comment]
It looks like the RPC is telling you that you're requesting too much data at once. Try setting `maxBlockRange` in your config. The error message says it can support up to 2k, so i would start with adding:
```
maxBlockRange: 2_000,
```

into your config

**Comment by 0xOlias** [comment]
More context - Ponder recognizes this error and retries it using the suggested range. The regression is that we are now incorrectly logging this as an error. I don't think there is any runtime/functional difference. We'll remove the log in a patch.

Cc @kyscott18, looks like this block is firing, even though we catch the error in the eth_getLogs helper function and handle it properly.
https://github.com/ponder-sh/ponder/blob/main/packages/core/src/utils/requestQueue.ts#L68-L74

**Comment by Inkvi** [comment]
So what happens when the error is thrown? Does ponder reduce the block range or just skips the blocks?

**Comment by 0xOlias** [comment]
Ponder parses the error string, divides the original block range into N smaller chunks according to a set of rules, and sends N new `eth_getLogs` requests. These requests usually succeed, so they do not log anything.

Here is the code: https://github.com/ponder-sh/ponder/blob/main/packages/utils/src/getLogsRetryHelper.ts

**Comment by Inkvi** [comment]
Lovely! I am going to use `maxBlockRange` just to be safe.
