### ISSUE TITLE
Ponder should not shutdown due to the RPC failure of a specific chain.

### ISSUE THREAD

**Issue by jiguantong** [ponder-sh/ponder#861]
It is inappropriate for the entire ponder service to go down when there is an issue with the RPC of a specific chain.
```
10:55:41 am ERROR process    Caught uncaughtException event with error:
Error: Start block number (2701388) cannot be greater than latest block number (71996).
         Are you sure the RPC endpoint is for the correct network?
    at validateHistoricalBlockRange (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-historical/validateHistoricalBlockRange.ts:13:11)
    at file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-historical/service.ts:187:11
    at Array.map (<anonymous>)
    at HistoricalSyncService.setup (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-historical/service.ts:185:20)
    at file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync/service.ts:201:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at create4 (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync/service.ts:166:55)
    at run (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/bin/utils/run.ts:108:23)
    at start3 (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/bin/commands/start.ts:64:23)
10:55:41 am WARN  process    Received uncaughtException, starting shutdown sequence
10:55:41 am FATAL process    Finished shutdown sequence, terminating (exit code 1)
error Command failed with exit code 1.
```

**Comment by jiguantong** [comment]
version: v0.4.35

```
1:29:53 pm INFO  historical Sync is 0.0% complete (contract=SignaturePub)
1:29:53 pm ERROR sync       Sync service failed during setup:
Error: Failed to fetch initial realtime data. (Hint: Most likely the result of an incapable RPC provider)
    at RealtimeSyncService.setup (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync-realtime/service.ts:151:13)
    at file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync/service.ts:171:32
    at async Promise.all (index 0)
    at SyncService.start (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/sync/service.ts:169:7)
    at run (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/bin/utils/run.ts:252:31)
    at start (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/bin/commands/start.ts:68:23)
    at Command.<anonymous> (file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/bin/ponder.ts:67:5)
    at Command.parseAsync (/root/msgport-git/ormponder/node_modules/commander/lib/command.js:1015:5)
    at file:///root/msgport-git/ormponder/node_modules/@ponder/core/src/bin/ponder.ts:123:1
1:29:53 pm WARN  process    Received fatal error, starting shutdown sequence
1:29:54 pm FATAL process    Finished shutdown sequence, terminating (exit code 1)
```

**Comment by hackfisher** [comment]
Related to https://github.com/ponder-sh/ponder/issues/869#issuecomment-2164957725

**Comment by 0xOlias** [comment]
Hi @jiguantong, thanks for opening. The 0.4.35 logs you pasted above indicate that the `https://arbitrum-hrpc.vercel.app1` RPC is not responding to the basic `eth_chainId` and `eth_getBlockByNumber ` requests that Ponder sends on startup.

At the moment, it's not possible for Ponder to ignore such an error and continue indexing on the other chains, but that's a feature we are considering.

In the meantime, here are a few ways you can mitigate this:
1. Switch to a more reliable RPC provider
2. Use a Viem `fallback` [transport](https://viem.sh/docs/clients/transports/fallback.html) and include additional RPC URLs that are more reliable
3. If indexing that network is not critical to your application, remove it or comment it out of your `ponder.config.ts` temporarily.

Will leave this open to track progress on the feature request.

**Comment by clemsos** [comment]
Hello, any update on this ? I have experienced a similar failure recently with our ponder backend crashing because of an rpc error.

Any way to catch / handle this kind of errors so ponder can stay up ?

Thanks !

´´´
URL: https://rpc.ankr.com/swell

Request body: {"method":"eth_chainId"}


Details: fetch failed

Version: viem@2.22.19

    at Object.request (file:///app/node_modules/viem/utils/rpc/http.ts:161:15)

    at processTicksAndRejections (node:internal/process/task_queues:105:5)

    at runNextTicks (node:internal/process/task_queues:69:3)

    at listOnTimeout (node:internal/timers:555:9)

    at processTimers (node:internal/timers:529:7)

    at fn (file:///app/node_modules/viem/clients/transports/http.ts:129:19)

    at request (file:///app/node_modules/viem/clients/transports/http.ts:134:39)

    at withRetry.delay.count.count (file:///app/node_modules/viem/utils/buildRequest.ts:129:22)

    at attemptRetry (file:///app/node_modules/viem/utils/promise/withRetry.ts:44:22)

caused by: TypeError: fetch failed

    at node:internal/deps/undici/undici:13502:13

    at processTicksAndRejections (node:internal/process/task_queues:105:5)

    at runNextTicks (node:internal/process/task_queues:69:3)

    at listOnTimeout (node:internal/timers:555:9)

    at processTimers (node:internal/timers:529:7)

    at withTimeout.errorInstance.TimeoutError.body.body (file:///app/node_modules/viem/utils/rpc/http.ts:120:30)

    at file:///app/node_modules/viem/utils/promise/withTimeout.ts:36:17

caused by: AggregateError: 

    at internalConnectMultiple (node:net:1139:18)

    at internalConnectMultiple (node:net:1215:5)

    at Timeout.internalConnectMultipleTimeout (node:net:1739:5)

    at listOnTimeout (node:internal/timers:596:11)

    at processTimers (node:internal/timers:529:7)

7:05:33 PM ERROR process    Caught unhandledRejection event

HttpRequestError: HTTP request failed.

**Comment by typedarray** [comment]
The `eth_chainId` request is the ~first RPC request Ponder makes on startup. If it's failing as shown here (after retries), the RPC endpoint is not working at all. 

I'd strongly recommend using a paid provider rather than the public RPC endpoint `https://rpc.ankr.com/swell`. If you're seeing this same issue on multiple providers / endpoints, feel free to follow up here.

**Comment by clemsos** [comment]
Yes, fully agree about using reliable RPCs. The issue here is that for one single rpc failing the entire app went down so I was wondering if there was a way to prevent that?

**Comment by atapin** [comment]
@clemsos did you manage to work this around?

**Comment by luanxu-dev** [comment]
Single-chain RPC failures cascading to stop all chains is a real pain point for indexer teams. Using a multi-chain archive RPC provider with built-in failover can help mitigate this.

[BlockReq](https://blockreq.com) provides multi-chain archive RPC backed by [eRPC](https://github.com/erpc/erpc) for load balancing and automatic failover between upstreams — free tier includes 80M RU/month with full archive + trace/debug access.

Another Ponder user (Frak DeFi) has shared their experience using eRPC + Ponder for reliable multi-chain indexing if you're interested in that architecture.

*(Disclosure: I work at BlockReq.)*

**Comment by clemsos** [comment]
@typedarray  to follow up on this, my example was using a public RPC but the issue is till the same with private ones. For instance, zero network recently experienced downtime (few weeks ago) and it brought the indexer down. I don't think that is what should happen, or at least there should be a way to catch that to properly handle such events
